#define WALL 32787
#define SIZE 20
#define INIT_X 0
#define INIT_Y 1
#define FINISH_X 1
#define FINISH_Y 19

extern int maze [SIZE][SIZE] =
{
    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
    {  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,WALL,WALL,WALL},
    {WALL,WALL,  0 ,WALL,WALL,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,  0 ,WALL,WALL,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,  0 ,WALL,  0 ,WALL,  0 ,  0 ,  0 ,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,  0 ,  0 ,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,WALL,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,WALL,WALL,  0 ,WALL,WALL,WALL},
    {WALL,WALL,WALL,WALL,WALL,WALL,  0 ,WALL,WALL,WALL},
    {WALL,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,WALL},
    {WALL,  0 ,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
    {WALL,  0 ,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
    {WALL,  0 ,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
};
